version: "3.9"

services:
  web:
    build: .
    env_file:
      - .env
    command: poetry run uvicorn src.main:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - .:/app
